FROM gradle:5.3
WORKDIR /src
USER root
RUN chown -R gradle:gradle /src
USER gradle
RUN git clone https://github.com/ondy/fiets.git ;\
  cd fiets; git checkout customized ;\
  gradle build

FROM ondy/fiets:latest
RUN mkdir -p classes/fiets/custom
COPY --from=0 --chown=fiets-user:fiets-user /src/fiets/build/classes/java/main/fiets/custom classes/fiets/custom
COPY --from=0 --chown=fiets-user:fiets-user /src/fiets/fiets.properties fiets.properties

